### ISSUE TITLE
Instructions for Apple SIlicon installation 

### ISSUE THREAD

**Issue by waterfleas** [sjbonner/mark-on-mac#1]
While mark-on-mac installs on Apple silicon without error, the path that homebrew installs software on is different:
Homebrew on Apple silicon = /opt/homebrew
Homebrew on intel = /usr/local
 [see debates on pros and cons of this on github](https://github.com/Homebrew/brew/issues/9177) 
This causes an error on launch
```
~ mark
/opt/homebrew/bin/mark: line 2: /usr/local/bin/mark.64.OSX: No such file or directory
```

The workaround is simple enough - utilise rosetta to install an intel version. Much easier than rewriting paths in mark

Before you start - remove the mark-on-mac from your current brew setup as it will be the default and screw everything up...
`brew uninstall mark-on-mac`

### Installing homebrew under rosetta
First, install rosetta - open a terminal and type 
`softwareupdate --install-rosetta` 
accept the agreement.

Install the intel version of homebrew
`arch --x86_64 /bin/bash -c "($curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Create an alias for easy use - I'm calling mine beer
`echo "alias beer='arch --x86_64 /usr/local/Homebrew/bin/brew'" >> ~/.zsh_aliases`

Either open a new terminal or source your aliases to enable
`source ~/.zsh_aliases`

From here the instructions are the same as the original:
`beer install gcc`
`beer tap sjbonner/tap`
`beer install mark-on-mac`

```
~ mark
 No input file was specified, so MARK job is done.
STOP No input file
```

**Comment by sjbonner** [comment]
Very cool! Thanks for working on this, @waterfleas. I'll add these notes to the installation instructions.
