### ISSUE TITLE
Error- Unable to find mark.exe on MacOS

### ISSUE THREAD

**Issue by nishantbhardwaj1** [sjbonner/mark-on-mac#2]
Hi, I used your script to install Mark on MacOS Ventura(intel chip). Homebrew and Xcode were installed successfully. After that I installed mark on Mac. When I used "which mark" I got this output- _/usr/local/bin/mark_

 But when I used "mark" command I did not get the same output as yours. I got this -_dyld[14329]: Library not loaded: /usr/local/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib_
After that I installed Mark package in Rstudio and used this command-_dipper.model <- mark(dipper)_. dipper is a dataset here.However I was not able to run it. It showed the error (see attached image). Would you please assist me in it?
<img width="635" alt="Screenshot 2023-05-31 at 11 59 23" src="https://github.com/sjbonner/mark-on-mac/assets/67380888/c9b0ea21-f376-4d96-b47d-b724da47e816">

**Comment by sjbonner** [comment]
@nishantbhardwaj1, can you confirm that you installed gcc (Step 2 in the instructions)?

**Comment by nishantbhardwaj1** [comment]
@sjbonner yes that's what I missed. I installed it after that and it is working now. I was able to solve it so I closed the issue. Thank you very much for your reply

**Comment by sjbonner** [comment]
Good news. Thanks @nishantbhardwaj1 !
