### ISSUE TITLE
/bin/bash: -fsSL: command not found

### ISSUE THREAD

**Issue by andrew-pettit** [sjbonner/mark-on-mac#3]
I have a M1 Mac and when I try to install the intel versions of homebrew I get this issue:

arch --x86_64 /bin/bash -c "($curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

/bin/bash: -fsSL: command not found

I haven't done anything ever to my terminal besides this. 

Thank you!

**Comment by sjbonner** [comment]
Hi @andrew-pettit. I believe there is a typo in the instructions. The $ should come before the ( not after. Can you try the following and let me know if it works?

`arch --x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Thanks!

**Comment by andrew-pettit** [comment]
That works! Thank you so much! I greatly appreciate it

**Comment by sjbonner** [comment]
Excellent. Thanks for helping to fix the bug.
