### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Habanero-Mora** [sjbonner/mark-on-mac#4]
I am having a very hard time understanding what I am doing wrong here. I need to download MARK for a grad school class and it is not going well. Can someone help me troubleshoot please

<img width="1187" alt="Screenshot 2024-08-16 at 8 01 41 PM" src="https://github.com/user-attachments/assets/5e402b7f-093b-4297-b2ed-28a0613e574f">
<img width="1184" alt="Screenshot 2024-08-16 at 8 02 11 PM" src="https://github.com/user-attachments/assets/74e161d9-e211-4a93-85f6-09093e33e9e3">

**Comment by sjbonner** [comment]
I haven't run mark recently, but I have exactly the same problem. It seems that the current version of mark for MacOS is out of date with gcc. Unfortunately, I don't have the code so I can't recompile it myself. I'll check with the powers that be.

BTW, you know that this only installs the command line version for use with RMark, right? Your class may require the gui version. If so, then you'll need to install a virtual machine to run windows.

**Comment by sjbonner** [comment]
Hey @Habanero-Mora. I've updated the version of Mark. It works for me now. 

Can you run the following and let me know what happens?

```
brew update
brew upgrade
mark
```

```
If the upgrade works the you should see something like this:
 No input file was specified, so MARK job is done.
MARK Files:
  i=input_file_name
  o=output_file_name
  r=residuals_file_name
  v=variance-covariance_file_name
MARK Parameters:
  nocolor    - do not use color on output screen
  noecho     - do not echo commands on output screen
  batch      - no output printed to output screen (i.e., batch mode)
  dynamic    - dynamic thread allocation used, otherwise static allocation used
  threads=x  - specify the number of threads to be used
                0 means use all available
               -1 means use all available minus 1
                otherwise use the number specified as x
  linex=x    - print x lines per page, default is 50
                0 means do not print page headers
STOP No input file
```

Thanks!

**Comment by sjbonner** [comment]
Tested myself on a clean machine. Install went smoothly and worked as expected.
