### ISSUE TITLE
Permission denied: mark

### ISSUE THREAD

**Issue by robynthomas1** [sjbonner/mark-on-mac#6]
Hello,

I keep getting the following when I try to open mark:

permission denied: mark

I have tried to follow the tutorial several times thinking that I might have missed a step but I am confident I have done everything as described. I am working on a Macbook air M2 (Silicon) so I followed the directions for installation on Apple Silicon based Macs. To my knowledge I don't have any special permissions set for my computer, has anyone run into this before? 

Any advice would be appreciated.

**Comment by sjbonner** [comment]
Hi @robynthomas1. It looks like the permissions for mark have not been set properly. I'm not sure why this would have happened.

Can you run the following command?

`ls -l "$( which mark )"`

The output should start with a string like:

`lrwxr-xr-x`

indicating the permissions. The last nine letters indicate the permissions for the mark binary. The `x`s indicate which users can run mark. If any are missing then you may not be able to run the executable (depending on which user installed it). You can make mark executable by all users by running:

`chmod a+x "$( which mark )"`

I can also take a look if you send me the output from the first command or you can also find out more about the permissions mean and how to change them online (e.g.[https://www.redhat.com/sysadmin/linux-file-permissions-explained]( https://www.redhat.com/sysadmin/linux-file-permissions-explained)).

**Comment by robynthomas1** [comment]
Hi @sjbonner, thanks for this. I deleted everything related to mark in my downloads and local bin and fully started over with your code advice and it worked. Thanks,

Robyn
